# Shared fonts used for all installationProfiles

defaultFonts=(
    font-clear-sans
    font-open-sans
    font-noto-sans
    font-roboto
    font-roboto-mono
    font-roboto-slab
    font-montserrat
    font-lato
    font-fira-code
    font-source-code-pro
    font-source-sans-3
    font-raleway
    font-oswald
    font-poppins
    font-merriweather
    font-pt-sans
    font-ubuntu
    font-cuprum
    font-oxygen
    font-redhat
    font-space-mono
    font-monoid
    font-milonga
    font-anton
    font-3270
    font-abel
    font-montserrat
    font-playfair-display    
)
